apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-by-kmpissuer
spec:
  commonName: certificate-by-kmpissuer.example.com
  secretName: certificate-by-kmpissuer
  issuerRef:
    name: kmpissuer-sample
    group: kmp.cert-manager.io
    kind: KMPIssuer
