/*
Copyright 2026 The kmp-issuer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	// KMPCertificateConditionReady reports whether the Secret holds a current
	// certificate.
	KMPCertificateConditionReady string = "Ready"

	// KMPCertificateConditionIssuing reports that an issuance is in progress or
	// was attempted.
	KMPCertificateConditionIssuing string = "Issuing"

	// KeyStorePasswordSecretKey is the key the generated key store password is
	// written to, in the target Secret, when the spec does not supply one.
	KeyStorePasswordSecretKey = "keystore-password"
)

// KMPCertificateSpec asks Key Manager Plus to generate a key pair and issue a
// certificate for it, and to keep the key in escrow.
//
// This is the counterpart of a cert-manager Certificate for deployments where
// Key Manager Plus is the key custodian: the private key is generated by Key
// Manager Plus, exported once, and written to the Secret alongside the
// certificate. When the cluster should own the key instead, use a cert-manager
// Certificate with a KMPIssuer, which never lets the key leave the cluster.
type KMPCertificateSpec struct {
	// SecretName is the Secret to write the certificate and its private key to,
	// in this namespace. It is created if it does not exist, and is owned by
	// this resource.
	//
	// +kubebuilder:validation:MinLength=1
	SecretName string `json:"secretName"`

	// IssuerRef names the KMPIssuer or KMPClusterIssuer that supplies the Key
	// Manager Plus endpoint, the credentials and the signing configuration.
	IssuerRef IssuerReference `json:"issuerRef"`

	// CommonName is the subject common name, sent as CNAME.
	//
	// +kubebuilder:validation:MinLength=1
	CommonName string `json:"commonName"`

	// DNSNames and IPAddresses become the subject alternative names, sent to
	// Key Manager Plus as the comma separated ALT_NAMES parameter.
	//
	// +optional
	DNSNames []string `json:"dnsNames,omitempty"`

	// +optional
	IPAddresses []string `json:"ipAddresses,omitempty"`

	// Subject is the rest of the distinguished name.
	//
	// +optional
	Subject CertificateSubject `json:"subject,omitempty"`

	// PrivateKey describes the key Key Manager Plus generates.
	//
	// +optional
	PrivateKey PrivateKeySpec `json:"privateKey,omitempty"`

	// ValidityDays is the requested lifetime, sent as VALIDITY. Microsoft CA
	// templates carry their own validity and ignore it.
	//
	// +kubebuilder:validation:Minimum=1
	// +optional
	ValidityDays *int32 `json:"validityDays,omitempty"`

	// ValidityType is sent as VALIDITY_TYPE.
	//
	// +optional
	ValidityType string `json:"validityType,omitempty"`

	// RenewBefore is how long before expiry a new certificate is requested.
	// Defaults to a third of the certificate's lifetime.
	//
	// +optional
	RenewBefore *metav1.Duration `json:"renewBefore,omitempty"`

	// KeyStorePasswordSecretRef holds the password protecting the key store Key
	// Manager Plus keeps the key in, which is also needed to export it. When
	// unset, a password is generated for each issuance and recorded in the
	// target Secret under "keystore-password", so that the key can still be
	// recovered from Key Manager Plus later.
	//
	// +optional
	KeyStorePasswordSecretRef *SecretKeySelector `json:"keyStorePasswordSecretRef,omitempty"`
}

// IssuerReference names an issuer in this API group.
type IssuerReference struct {
	// Name of the issuer.
	//
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Kind of the issuer, either KMPIssuer or KMPClusterIssuer.
	//
	// +kubebuilder:validation:Enum=KMPIssuer;KMPClusterIssuer
	// +kubebuilder:default=KMPIssuer
	// +optional
	Kind string `json:"kind,omitempty"`
}

// CertificateSubject is the distinguished name beyond the common name.
type CertificateSubject struct {
	// Organization is sent as ORG.
	// +optional
	Organization string `json:"organization,omitempty"`

	// OrganizationalUnit is sent as ORGUNIT.
	// +optional
	OrganizationalUnit string `json:"organizationalUnit,omitempty"`

	// Locality is sent as LOCATION.
	// +optional
	Locality string `json:"locality,omitempty"`

	// Province is sent as STATE.
	// +optional
	Province string `json:"province,omitempty"`

	// Country is sent as COUNTRY.
	// +optional
	Country string `json:"country,omitempty"`
}

// PrivateKeySpec describes the key Key Manager Plus generates.
type PrivateKeySpec struct {
	// Algorithm is sent as ALG.
	//
	// +kubebuilder:validation:Enum=RSA;EC
	// +kubebuilder:default=RSA
	// +optional
	Algorithm string `json:"algorithm,omitempty"`

	// Size is the key length, sent as LEN.
	//
	// +kubebuilder:validation:Minimum=256
	// +kubebuilder:default=2048
	// +optional
	Size *int32 `json:"size,omitempty"`

	// SignatureAlgorithm is sent as SIGALG.
	//
	// +kubebuilder:default=SHA256
	// +optional
	SignatureAlgorithm string `json:"signatureAlgorithm,omitempty"`

	// StoreType is the key store format Key Manager Plus keeps the key in, sent
	// as StoreType. The key is exported as PEM regardless; this controller
	// cannot open a key store, so an export that returns one fails with an
	// explanation.
	//
	// +kubebuilder:default=PKCS12
	// +optional
	StoreType string `json:"storeType,omitempty"`
}

// SecretKeySelector references one key of one Secret in the same namespace.
type SecretKeySelector struct {
	// Name of the Secret.
	//
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Key within the Secret. Defaults to "password".
	//
	// +optional
	Key string `json:"key,omitempty"`
}

// KMPCertificateStatus reports what was issued.
type KMPCertificateStatus struct {
	// Conditions holds the observed state.
	//
	// +optional
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// SerialNumber of the issued certificate, as Key Manager Plus reported it.
	// +optional
	SerialNumber string `json:"serialNumber,omitempty"`

	// CSRID is the Key Manager Plus record holding the escrowed key.
	// +optional
	CSRID string `json:"csrID,omitempty"`

	// NotBefore and NotAfter are the validity window of the issued certificate.
	// +optional
	NotBefore *metav1.Time `json:"notBefore,omitempty"`
	// +optional
	NotAfter *metav1.Time `json:"notAfter,omitempty"`

	// RenewalTime is when a replacement will be requested.
	// +optional
	RenewalTime *metav1.Time `json:"renewalTime,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Secret",type="string",JSONPath=".spec.secretName"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type==\"Ready\")].status"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type==\"Ready\")].reason"
// +kubebuilder:printcolumn:name="Expires",type="date",JSONPath=".status.notAfter"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// KMPCertificate is a certificate whose private key is generated and kept by
// ManageEngine Key Manager Plus.
type KMPCertificate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   KMPCertificateSpec   `json:"spec,omitempty"`
	Status KMPCertificateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KMPCertificateList contains a list of KMPCertificate.
type KMPCertificateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KMPCertificate `json:"items"`
}
