/*
Copyright 2026 The kmp-issuer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package kmp

import (
	"context"
	"crypto"
	"crypto/x509"
	"fmt"
	"net"
	"strings"
)

// ProvisionRequest asks Key Manager Plus to generate a key pair, sign a
// certificate for it and hand both back.
//
// This is the escrowed-key flow: the key is generated by Key Manager Plus,
// which keeps a copy, rather than in the cluster.
type ProvisionRequest struct {
	// CommonName and AltNames make up the identity of the certificate.
	CommonName string
	AltNames   []string

	// Organization, OrganizationalUnit, Location, State and Country complete
	// the subject.
	Organization       string
	OrganizationalUnit string
	Location           string
	State              string
	Country            string

	// KeyAlgorithm, KeyLength and SignatureAlgorithm describe the key Key
	// Manager Plus generates.
	KeyAlgorithm       string
	KeyLength          int32
	SignatureAlgorithm string

	// StoreType is the key store format Key Manager Plus keeps the key in.
	StoreType string

	// ValidityType and ValidityDays are passed to createCSR.
	ValidityType string
	ValidityDays *int32

	// Password protects the stored key and is needed to export it.
	Password string

	// ExportFileType selects what exportCSR returns; defaults to PrivateKey.
	ExportFileType string
}

// ProvisionedCertificate is a certificate together with the key Key Manager
// Plus generated for it.
type ProvisionedCertificate struct {
	// Bundle holds the certificate chain, leaf first.
	Bundle *Bundle
	// PrivateKeyPEM is the escrowed key, as an unencrypted PKCS#8 PEM block.
	PrivateKeyPEM []byte
	// CSRID is the Key Manager Plus record the key and certificate belong to.
	CSRID string
	// SerialNumber identifies the issued certificate in Key Manager Plus.
	SerialNumber string
}

// Provision runs the escrowed-key flow: createCSR generates the key pair and
// the request, signCSR signs it, getCertificate fetches the certificate and
// exportCSR retrieves the private key.
//
// The key and the certificate are checked against each other before they are
// returned, so a mismatched pair is never published.
func (s *Signer) Provision(ctx context.Context, req ProvisionRequest) (*ProvisionedCertificate, error) {
	if strings.TrimSpace(req.CommonName) == "" {
		return nil, fmt.Errorf("%w: the request has no common name", ErrInvalidConfig)
	}
	if req.Password == "" {
		return nil, fmt.Errorf("%w: no password to protect the key Key Manager Plus generates", ErrInvalidConfig)
	}

	stored, err := s.client.CreateCSR(ctx, CreateCSRRequest{
		CommonName:         req.CommonName,
		AltNames:           req.AltNames,
		Organization:       req.Organization,
		OrganizationalUnit: req.OrganizationalUnit,
		Location:           req.Location,
		State:              req.State,
		Country:            req.Country,
		Password:           req.Password,
		KeyAlgorithm:       req.KeyAlgorithm,
		KeyLength:          req.KeyLength,
		SignatureAlgorithm: req.SignatureAlgorithm,
		StoreType:          req.StoreType,
		ValidityType:       req.ValidityType,
		ValidityDays:       req.ValidityDays,
	})
	if err != nil {
		return nil, fmt.Errorf("creating the certificate signing request: %w", err)
	}

	csrID, err := s.resolveCSRID(ctx, stored, req.CommonName)
	if err != nil {
		return nil, err
	}

	result, err := s.client.SignCSR(ctx, s.signRequest(csrID, Request{IsCA: false}))
	if err != nil {
		return nil, fmt.Errorf("signing the certificate signing request: %w", err)
	}

	commonName := result.CommonName
	if commonName == "" {
		commonName = req.CommonName
	}

	certs, err := s.fetchCertificate(ctx, commonName, result.SerialNumber)
	if err != nil {
		return nil, fmt.Errorf("fetching the signed certificate: %w", err)
	}

	exported, err := s.client.ExportCSR(ctx, csrID, req.ExportFileType)
	if err != nil {
		return nil, fmt.Errorf("exporting the private key: %w", err)
	}
	privateKey, err := ParseExportedPrivateKey(exported, req.Password)
	if err != nil {
		return nil, fmt.Errorf("%w: reading the exported private key: %s", ErrUnusableResponse, err)
	}

	var publicKey crypto.PublicKey
	if signer, ok := privateKey.Key.(interface{ Public() crypto.PublicKey }); ok {
		publicKey = signer.Public()
	}
	bundle, err := BuildBundle(certs, publicKey)
	if err != nil {
		return nil, fmt.Errorf("%w: assembling the certificate chain: %s", ErrUnusableResponse, err)
	}
	if !privateKey.MatchesCertificate(bundle.Leaf) {
		return nil, fmt.Errorf("%w: the exported private key does not belong to the issued certificate", ErrUnusableResponse)
	}
	if err := verifyProvisionedNames(req, bundle.Leaf); err != nil {
		return nil, err
	}

	return &ProvisionedCertificate{
		Bundle:        bundle,
		PrivateKeyPEM: privateKey.PEM,
		CSRID:         csrID,
		SerialNumber:  result.SerialNumber,
	}, nil
}

// verifyProvisionedNames reports identities that were asked for but are missing
// from the issued certificate, as a Microsoft CA template that builds the
// subject itself would cause.
func verifyProvisionedNames(req ProvisionRequest, leaf *x509.Certificate) error {
	var missing []string

	if !strings.EqualFold(req.CommonName, leaf.Subject.CommonName) {
		missing = append(missing, fmt.Sprintf("common name %q (the certificate has %q)", req.CommonName, leaf.Subject.CommonName))
	}

	for _, name := range req.AltNames {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		if ip := net.ParseIP(name); ip != nil {
			found := false
			for _, issued := range leaf.IPAddresses {
				if issued.Equal(ip) {
					found = true
					break
				}
			}
			if !found {
				missing = append(missing, fmt.Sprintf("IP address %q", name))
			}
			continue
		}
		if !containsFold(leaf.DNSNames, name) {
			missing = append(missing, fmt.Sprintf("DNS name %q", name))
		}
	}

	if len(missing) == 0 {
		return nil
	}
	return fmt.Errorf("%w: key manager plus returned a certificate that is missing %s. "+
		"A Microsoft CA template only keeps the subject and the subject alternative names of a request "+
		"when it is configured to supply them from the request",
		ErrUnusableResponse, strings.Join(missing, ", "))
}
